//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.31 at 11:14:56 AM EDT 
//


package com.dsd.parser;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dsd.parser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dsd.parser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SSNExportDocument }
     * 
     */
    public SSNExportDocument createSSNExportDocument() {
        return new SSNExportDocument();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData }
     * 
     */
    public SSNExportDocument.MeterData createSSNExportDocumentMeterData() {
        return new SSNExportDocument.MeterData();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.EventData }
     * 
     */
    public SSNExportDocument.MeterData.EventData createSSNExportDocumentMeterDataEventData() {
        return new SSNExportDocument.MeterData.EventData();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.IntervalReadData }
     * 
     */
    public SSNExportDocument.MeterData.IntervalReadData createSSNExportDocumentMeterDataIntervalReadData() {
        return new SSNExportDocument.MeterData.IntervalReadData();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.IntervalReadData.Interval }
     * 
     */
    public SSNExportDocument.MeterData.IntervalReadData.Interval createSSNExportDocumentMeterDataIntervalReadDataInterval() {
        return new SSNExportDocument.MeterData.IntervalReadData.Interval();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.RegisterData }
     * 
     */
    public SSNExportDocument.MeterData.RegisterData createSSNExportDocumentMeterDataRegisterData() {
        return new SSNExportDocument.MeterData.RegisterData();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.RegisterData.RegisterRead }
     * 
     */
    public SSNExportDocument.MeterData.RegisterData.RegisterRead createSSNExportDocumentMeterDataRegisterDataRegisterRead() {
        return new SSNExportDocument.MeterData.RegisterData.RegisterRead();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier }
     * 
     */
    public SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier createSSNExportDocumentMeterDataRegisterDataRegisterReadTier() {
        return new SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.EventData.Event }
     * 
     */
    public SSNExportDocument.MeterData.EventData.Event createSSNExportDocumentMeterDataEventDataEvent() {
        return new SSNExportDocument.MeterData.EventData.Event();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.IntervalReadData.Interval.Reading }
     * 
     */
    public SSNExportDocument.MeterData.IntervalReadData.Interval.Reading createSSNExportDocumentMeterDataIntervalReadDataIntervalReading() {
        return new SSNExportDocument.MeterData.IntervalReadData.Interval.Reading();
    }

    /**
     * Create an instance of {@link SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier.Register }
     * 
     */
    public SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier.Register createSSNExportDocumentMeterDataRegisterDataRegisterReadTierRegister() {
        return new SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier.Register();
    }

}
