//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.31 at 11:14:56 AM EDT 
//


package com.dsd.parser;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MeterData" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RegisterData">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RegisterRead" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Tier" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Register" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                         &lt;attribute name="Summation" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                                         &lt;attribute name="SummationUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="DemandUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="MaximumDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                                         &lt;attribute name="MaximumDemandTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="CumulativeDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="ReadTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="RegisterReadSource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Season" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="NumberReads" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="IntervalReadData">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Interval" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Reading" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="Channel" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="RawValue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                               &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="BlockEndValue" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="BlockSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="IntervalSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="IntervalLength" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="NumberIntervals" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EventData">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Event" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="EventName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="EventTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="NumberEvents" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="MeterName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="UtilDeviceID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MacID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="DocumentID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExportID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JobID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RunID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CreationTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "meterData"
})
@XmlRootElement(name = "SSNExportDocument")
public class SSNExportDocument {

    @XmlElement(name = "MeterData", required = true)
    protected List<SSNExportDocument.MeterData> meterData;
    @XmlAttribute(name = "Version")
    protected Double version;
    @XmlAttribute(name = "DocumentID")
    protected String documentID;
    @XmlAttribute(name = "ExportID")
    protected String exportID;
    @XmlAttribute(name = "JobID")
    protected Integer jobID;
    @XmlAttribute(name = "RunID")
    protected Integer runID;
    @XmlAttribute(name = "CreationTime")
    protected String creationTime;
    @XmlAttribute(name = "StartTime")
    protected String startTime;
    @XmlAttribute(name = "EndTime")
    protected String endTime;

    /**
     * Gets the value of the meterData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meterData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeterData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SSNExportDocument.MeterData }
     * 
     * 
     */
    public List<SSNExportDocument.MeterData> getMeterData() {
        if (meterData == null) {
            meterData = new ArrayList<SSNExportDocument.MeterData>();
        }
        return this.meterData;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVersion(Double value) {
        this.version = value;
    }

    /**
     * Gets the value of the documentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentID(String value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the exportID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportID() {
        return exportID;
    }

    /**
     * Sets the value of the exportID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportID(String value) {
        this.exportID = value;
    }

    /**
     * Gets the value of the jobID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJobID() {
        return jobID;
    }

    /**
     * Sets the value of the jobID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJobID(Integer value) {
        this.jobID = value;
    }

    /**
     * Gets the value of the runID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRunID() {
        return runID;
    }

    /**
     * Sets the value of the runID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRunID(Integer value) {
        this.runID = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RegisterData">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RegisterRead" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Tier" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Register" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                               &lt;attribute name="Summation" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                               &lt;attribute name="SummationUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="DemandUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="MaximumDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                               &lt;attribute name="MaximumDemandTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="CumulativeDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="ReadTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="RegisterReadSource" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Season" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="NumberReads" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="IntervalReadData">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Interval" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Reading" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="Channel" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="RawValue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                     &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="BlockEndValue" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="BlockSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="IntervalSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="IntervalLength" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="NumberIntervals" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EventData">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Event" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="EventName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="EventTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="NumberEvents" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="MeterName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="UtilDeviceID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MacID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "registerData",
        "intervalReadData",
        "eventData"
    })
    public static class MeterData {

        @XmlElement(name = "RegisterData", required = true)
        protected SSNExportDocument.MeterData.RegisterData registerData;
        @XmlElement(name = "IntervalReadData", required = true)
        protected SSNExportDocument.MeterData.IntervalReadData intervalReadData;
        @XmlElement(name = "EventData", required = true)
        protected SSNExportDocument.MeterData.EventData eventData;
        @XmlAttribute(name = "MeterName")
        protected String meterName;
        @XmlAttribute(name = "UtilDeviceID")
        protected String utilDeviceID;
        @XmlAttribute(name = "MacID")
        protected String macID;

        /**
         * Gets the value of the registerData property.
         * 
         * @return
         *     possible object is
         *     {@link SSNExportDocument.MeterData.RegisterData }
         *     
         */
        public SSNExportDocument.MeterData.RegisterData getRegisterData() {
            return registerData;
        }

        /**
         * Sets the value of the registerData property.
         * 
         * @param value
         *     allowed object is
         *     {@link SSNExportDocument.MeterData.RegisterData }
         *     
         */
        public void setRegisterData(SSNExportDocument.MeterData.RegisterData value) {
            this.registerData = value;
        }

        /**
         * Gets the value of the intervalReadData property.
         * 
         * @return
         *     possible object is
         *     {@link SSNExportDocument.MeterData.IntervalReadData }
         *     
         */
        public SSNExportDocument.MeterData.IntervalReadData getIntervalReadData() {
            return intervalReadData;
        }

        /**
         * Sets the value of the intervalReadData property.
         * 
         * @param value
         *     allowed object is
         *     {@link SSNExportDocument.MeterData.IntervalReadData }
         *     
         */
        public void setIntervalReadData(SSNExportDocument.MeterData.IntervalReadData value) {
            this.intervalReadData = value;
        }

        /**
         * Gets the value of the eventData property.
         * 
         * @return
         *     possible object is
         *     {@link SSNExportDocument.MeterData.EventData }
         *     
         */
        public SSNExportDocument.MeterData.EventData getEventData() {
            return eventData;
        }

        /**
         * Sets the value of the eventData property.
         * 
         * @param value
         *     allowed object is
         *     {@link SSNExportDocument.MeterData.EventData }
         *     
         */
        public void setEventData(SSNExportDocument.MeterData.EventData value) {
            this.eventData = value;
        }

        /**
         * Gets the value of the meterName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeterName() {
            return meterName;
        }

        /**
         * Sets the value of the meterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeterName(String value) {
            this.meterName = value;
        }

        /**
         * Gets the value of the utilDeviceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUtilDeviceID() {
            return utilDeviceID;
        }

        /**
         * Sets the value of the utilDeviceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUtilDeviceID(String value) {
            this.utilDeviceID = value;
        }

        /**
         * Gets the value of the macID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMacID() {
            return macID;
        }

        /**
         * Sets the value of the macID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMacID(String value) {
            this.macID = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Event" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="EventName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="EventTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="NumberEvents" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "event"
        })
        public static class EventData {

            @XmlElement(name = "Event", required = true)
            protected List<SSNExportDocument.MeterData.EventData.Event> event;
            @XmlAttribute(name = "StartTime")
            protected String startTime;
            @XmlAttribute(name = "EndTime")
            protected String endTime;
            @XmlAttribute(name = "NumberEvents")
            protected Integer numberEvents;

            /**
             * Gets the value of the event property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the event property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEvent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SSNExportDocument.MeterData.EventData.Event }
             * 
             * 
             */
            public List<SSNExportDocument.MeterData.EventData.Event> getEvent() {
                if (event == null) {
                    event = new ArrayList<SSNExportDocument.MeterData.EventData.Event>();
                }
                return this.event;
            }

            /**
             * Gets the value of the startTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartTime() {
                return startTime;
            }

            /**
             * Sets the value of the startTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartTime(String value) {
                this.startTime = value;
            }

            /**
             * Gets the value of the endTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndTime() {
                return endTime;
            }

            /**
             * Sets the value of the endTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndTime(String value) {
                this.endTime = value;
            }

            /**
             * Gets the value of the numberEvents property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNumberEvents() {
                return numberEvents;
            }

            /**
             * Sets the value of the numberEvents property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNumberEvents(Integer value) {
                this.numberEvents = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="EventName" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="EventTime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Event {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "EventName")
                protected String eventName;
                @XmlAttribute(name = "EventTime")
                protected String eventTime;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the eventName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEventName() {
                    return eventName;
                }

                /**
                 * Sets the value of the eventName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEventName(String value) {
                    this.eventName = value;
                }

                /**
                 * Gets the value of the eventTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEventTime() {
                    return eventTime;
                }

                /**
                 * Sets the value of the eventTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEventTime(String value) {
                    this.eventTime = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Interval" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Reading" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="Channel" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="RawValue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                           &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="BlockEndValue" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="BlockSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="IntervalSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="IntervalLength" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="NumberIntervals" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "interval"
        })
        public static class IntervalReadData {

            @XmlElement(name = "Interval", required = true)
            protected List<SSNExportDocument.MeterData.IntervalReadData.Interval> interval;
            @XmlAttribute(name = "IntervalLength")
            protected Integer intervalLength;
            @XmlAttribute(name = "StartTime")
            protected String startTime;
            @XmlAttribute(name = "EndTime")
            protected String endTime;
            @XmlAttribute(name = "NumberIntervals")
            protected Integer numberIntervals;

            /**
             * Gets the value of the interval property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the interval property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInterval().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SSNExportDocument.MeterData.IntervalReadData.Interval }
             * 
             * 
             */
            public List<SSNExportDocument.MeterData.IntervalReadData.Interval> getInterval() {
                if (interval == null) {
                    interval = new ArrayList<SSNExportDocument.MeterData.IntervalReadData.Interval>();
                }
                return this.interval;
            }

            /**
             * Gets the value of the intervalLength property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIntervalLength() {
                return intervalLength;
            }

            /**
             * Sets the value of the intervalLength property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIntervalLength(Integer value) {
                this.intervalLength = value;
            }

            /**
             * Gets the value of the startTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartTime() {
                return startTime;
            }

            /**
             * Sets the value of the startTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartTime(String value) {
                this.startTime = value;
            }

            /**
             * Gets the value of the endTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndTime() {
                return endTime;
            }

            /**
             * Sets the value of the endTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndTime(String value) {
                this.endTime = value;
            }

            /**
             * Gets the value of the numberIntervals property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNumberIntervals() {
                return numberIntervals;
            }

            /**
             * Sets the value of the numberIntervals property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNumberIntervals(Integer value) {
                this.numberIntervals = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Reading" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="Channel" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="RawValue" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                 &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="BlockEndValue" type="{http://www.w3.org/2001/XMLSchema}double" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="BlockSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="IntervalSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "reading"
            })
            public static class Interval {

                @XmlElement(name = "Reading", required = true)
                protected List<SSNExportDocument.MeterData.IntervalReadData.Interval.Reading> reading;
                @XmlAttribute(name = "EndTime")
                protected String endTime;
                @XmlAttribute(name = "GatewayCollectedTime")
                protected String gatewayCollectedTime;
                @XmlAttribute(name = "BlockSequenceNumber")
                protected Integer blockSequenceNumber;
                @XmlAttribute(name = "IntervalSequenceNumber")
                protected Integer intervalSequenceNumber;

                /**
                 * Gets the value of the reading property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the reading property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getReading().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link SSNExportDocument.MeterData.IntervalReadData.Interval.Reading }
                 * 
                 * 
                 */
                public List<SSNExportDocument.MeterData.IntervalReadData.Interval.Reading> getReading() {
                    if (reading == null) {
                        reading = new ArrayList<SSNExportDocument.MeterData.IntervalReadData.Interval.Reading>();
                    }
                    return this.reading;
                }

                /**
                 * Gets the value of the endTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEndTime() {
                    return endTime;
                }

                /**
                 * Sets the value of the endTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEndTime(String value) {
                    this.endTime = value;
                }

                /**
                 * Gets the value of the gatewayCollectedTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGatewayCollectedTime() {
                    return gatewayCollectedTime;
                }

                /**
                 * Sets the value of the gatewayCollectedTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGatewayCollectedTime(String value) {
                    this.gatewayCollectedTime = value;
                }

                /**
                 * Gets the value of the blockSequenceNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getBlockSequenceNumber() {
                    return blockSequenceNumber;
                }

                /**
                 * Sets the value of the blockSequenceNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setBlockSequenceNumber(Integer value) {
                    this.blockSequenceNumber = value;
                }

                /**
                 * Gets the value of the intervalSequenceNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getIntervalSequenceNumber() {
                    return intervalSequenceNumber;
                }

                /**
                 * Sets the value of the intervalSequenceNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setIntervalSequenceNumber(Integer value) {
                    this.intervalSequenceNumber = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="Channel" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="RawValue" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *       &lt;attribute name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="BlockEndValue" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Reading {

                    @XmlAttribute(name = "Channel")
                    protected Integer channel;
                    @XmlAttribute(name = "RawValue")
                    protected Integer rawValue;
                    @XmlAttribute(name = "Value")
                    protected Double value;
                    @XmlAttribute(name = "UOM")
                    protected String uom;
                    @XmlAttribute(name = "BlockEndValue")
                    protected Double blockEndValue;

                    /**
                     * Gets the value of the channel property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getChannel() {
                        return channel;
                    }

                    /**
                     * Sets the value of the channel property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setChannel(Integer value) {
                        this.channel = value;
                    }

                    /**
                     * Gets the value of the rawValue property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getRawValue() {
                        return rawValue;
                    }

                    /**
                     * Sets the value of the rawValue property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setRawValue(Integer value) {
                        this.rawValue = value;
                    }

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public Double getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setValue(Double value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the uom property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUOM() {
                        return uom;
                    }

                    /**
                     * Sets the value of the uom property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUOM(String value) {
                        this.uom = value;
                    }

                    /**
                     * Gets the value of the blockEndValue property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public Double getBlockEndValue() {
                        return blockEndValue;
                    }

                    /**
                     * Sets the value of the blockEndValue property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setBlockEndValue(Double value) {
                        this.blockEndValue = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RegisterRead" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Tier" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Register" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                                     &lt;attribute name="Summation" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                                     &lt;attribute name="SummationUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="DemandUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="MaximumDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                                     &lt;attribute name="MaximumDemandTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="CumulativeDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="ReadTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="RegisterReadSource" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Season" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="NumberReads" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "registerRead"
        })
        public static class RegisterData {

            @XmlElement(name = "RegisterRead", required = true)
            protected List<SSNExportDocument.MeterData.RegisterData.RegisterRead> registerRead;
            @XmlAttribute(name = "StartTime")
            protected String startTime;
            @XmlAttribute(name = "EndTime")
            protected String endTime;
            @XmlAttribute(name = "NumberReads")
            protected Integer numberReads;

            /**
             * Gets the value of the registerRead property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the registerRead property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRegisterRead().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SSNExportDocument.MeterData.RegisterData.RegisterRead }
             * 
             * 
             */
            public List<SSNExportDocument.MeterData.RegisterData.RegisterRead> getRegisterRead() {
                if (registerRead == null) {
                    registerRead = new ArrayList<SSNExportDocument.MeterData.RegisterData.RegisterRead>();
                }
                return this.registerRead;
            }

            /**
             * Gets the value of the startTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartTime() {
                return startTime;
            }

            /**
             * Sets the value of the startTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartTime(String value) {
                this.startTime = value;
            }

            /**
             * Gets the value of the endTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndTime() {
                return endTime;
            }

            /**
             * Sets the value of the endTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndTime(String value) {
                this.endTime = value;
            }

            /**
             * Gets the value of the numberReads property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNumberReads() {
                return numberReads;
            }

            /**
             * Sets the value of the numberReads property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNumberReads(Integer value) {
                this.numberReads = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Tier" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Register" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                           &lt;attribute name="Summation" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                           &lt;attribute name="SummationUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="DemandUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="MaximumDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                           &lt;attribute name="MaximumDemandTime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="CumulativeDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="ReadTime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="GatewayCollectedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="RegisterReadSource" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Season" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tier"
            })
            public static class RegisterRead {

                @XmlElement(name = "Tier", required = true)
                protected List<SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier> tier;
                @XmlAttribute(name = "ReadTime")
                protected String readTime;
                @XmlAttribute(name = "GatewayCollectedTime")
                protected String gatewayCollectedTime;
                @XmlAttribute(name = "RegisterReadSource")
                protected String registerReadSource;
                @XmlAttribute(name = "Season")
                protected Integer season;

                /**
                 * Gets the value of the tier property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the tier property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTier().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier }
                 * 
                 * 
                 */
                public List<SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier> getTier() {
                    if (tier == null) {
                        tier = new ArrayList<SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier>();
                    }
                    return this.tier;
                }

                /**
                 * Gets the value of the readTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReadTime() {
                    return readTime;
                }

                /**
                 * Sets the value of the readTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReadTime(String value) {
                    this.readTime = value;
                }

                /**
                 * Gets the value of the gatewayCollectedTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGatewayCollectedTime() {
                    return gatewayCollectedTime;
                }

                /**
                 * Sets the value of the gatewayCollectedTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGatewayCollectedTime(String value) {
                    this.gatewayCollectedTime = value;
                }

                /**
                 * Gets the value of the registerReadSource property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRegisterReadSource() {
                    return registerReadSource;
                }

                /**
                 * Sets the value of the registerReadSource property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRegisterReadSource(String value) {
                    this.registerReadSource = value;
                }

                /**
                 * Gets the value of the season property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getSeason() {
                    return season;
                }

                /**
                 * Sets the value of the season property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setSeason(Integer value) {
                    this.season = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Register" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *                 &lt;attribute name="Summation" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *                 &lt;attribute name="SummationUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="DemandUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="MaximumDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *                 &lt;attribute name="MaximumDemandTime" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="CumulativeDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "register"
                })
                public static class Tier {

                    @XmlElement(name = "Register", required = true)
                    protected List<SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier.Register> register;
                    @XmlAttribute(name = "Number")
                    protected Integer number;

                    /**
                     * Gets the value of the register property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the register property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getRegister().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier.Register }
                     * 
                     * 
                     */
                    public List<SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier.Register> getRegister() {
                        if (register == null) {
                            register = new ArrayList<SSNExportDocument.MeterData.RegisterData.RegisterRead.Tier.Register>();
                        }
                        return this.register;
                    }

                    /**
                     * Gets the value of the number property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getNumber() {
                        return number;
                    }

                    /**
                     * Sets the value of the number property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setNumber(Integer value) {
                        this.number = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
                     *       &lt;attribute name="Summation" type="{http://www.w3.org/2001/XMLSchema}double" />
                     *       &lt;attribute name="SummationUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="DemandUOM" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="MaximumDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
                     *       &lt;attribute name="MaximumDemandTime" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="CumulativeDemand" type="{http://www.w3.org/2001/XMLSchema}double" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Register {

                        @XmlAttribute(name = "Number")
                        protected Integer number;
                        @XmlAttribute(name = "Summation")
                        protected Double summation;
                        @XmlAttribute(name = "SummationUOM")
                        protected String summationUOM;
                        @XmlAttribute(name = "DemandUOM")
                        protected String demandUOM;
                        @XmlAttribute(name = "MaximumDemand")
                        protected Double maximumDemand;
                        @XmlAttribute(name = "MaximumDemandTime")
                        protected String maximumDemandTime;
                        @XmlAttribute(name = "CumulativeDemand")
                        protected Double cumulativeDemand;

                        /**
                         * Gets the value of the number property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Integer }
                         *     
                         */
                        public Integer getNumber() {
                            return number;
                        }

                        /**
                         * Sets the value of the number property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Integer }
                         *     
                         */
                        public void setNumber(Integer value) {
                            this.number = value;
                        }

                        /**
                         * Gets the value of the summation property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Double }
                         *     
                         */
                        public Double getSummation() {
                            return summation;
                        }

                        /**
                         * Sets the value of the summation property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Double }
                         *     
                         */
                        public void setSummation(Double value) {
                            this.summation = value;
                        }

                        /**
                         * Gets the value of the summationUOM property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSummationUOM() {
                            return summationUOM;
                        }

                        /**
                         * Sets the value of the summationUOM property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSummationUOM(String value) {
                            this.summationUOM = value;
                        }

                        /**
                         * Gets the value of the demandUOM property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getDemandUOM() {
                            return demandUOM;
                        }

                        /**
                         * Sets the value of the demandUOM property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setDemandUOM(String value) {
                            this.demandUOM = value;
                        }

                        /**
                         * Gets the value of the maximumDemand property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Double }
                         *     
                         */
                        public Double getMaximumDemand() {
                            return maximumDemand;
                        }

                        /**
                         * Sets the value of the maximumDemand property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Double }
                         *     
                         */
                        public void setMaximumDemand(Double value) {
                            this.maximumDemand = value;
                        }

                        /**
                         * Gets the value of the maximumDemandTime property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getMaximumDemandTime() {
                            return maximumDemandTime;
                        }

                        /**
                         * Sets the value of the maximumDemandTime property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setMaximumDemandTime(String value) {
                            this.maximumDemandTime = value;
                        }

                        /**
                         * Gets the value of the cumulativeDemand property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Double }
                         *     
                         */
                        public Double getCumulativeDemand() {
                            return cumulativeDemand;
                        }

                        /**
                         * Sets the value of the cumulativeDemand property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Double }
                         *     
                         */
                        public void setCumulativeDemand(Double value) {
                            this.cumulativeDemand = value;
                        }

                    }

                }

            }

        }

    }

}
