/*
 * This file is generated by jOOQ.
*/
package com.dsd.db;


import com.dsd.db.tables.Device;
import com.dsd.db.tables.Deviceevents;
import com.dsd.db.tables.Intervalreads;
import com.dsd.db.tables.Registerreads;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>MeterDataStore</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DEVICE_PRIMARY = Indexes0.DEVICE_PRIMARY;
    public static final Index DEVICEEVENTS_FK_DEVICEEVENTS_1_IDX = Indexes0.DEVICEEVENTS_FK_DEVICEEVENTS_1_IDX;
    public static final Index DEVICEEVENTS_UK_DEVICEEVENTS = Indexes0.DEVICEEVENTS_UK_DEVICEEVENTS;
    public static final Index INTERVALREADS_FK_INTERVALREADS_1_IDX = Indexes0.INTERVALREADS_FK_INTERVALREADS_1_IDX;
    public static final Index INTERVALREADS_UK_INTERVAL_READ = Indexes0.INTERVALREADS_UK_INTERVAL_READ;
    public static final Index REGISTERREADS_FK_REGISTERREADS_1_IDX = Indexes0.REGISTERREADS_FK_REGISTERREADS_1_IDX;
    public static final Index REGISTERREADS_UK_REGISTER_KEY = Indexes0.REGISTERREADS_UK_REGISTER_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index DEVICE_PRIMARY = createIndex("PRIMARY", Device.DEVICE, new OrderField[] { Device.DEVICE.SERIALNUMBER }, true);
        public static Index DEVICEEVENTS_FK_DEVICEEVENTS_1_IDX = createIndex("fk_deviceEvents_1_idx", Deviceevents.DEVICEEVENTS, new OrderField[] { Deviceevents.DEVICEEVENTS.DEVICEID }, false);
        public static Index DEVICEEVENTS_UK_DEVICEEVENTS = createIndex("uk_deviceevents", Deviceevents.DEVICEEVENTS, new OrderField[] { Deviceevents.DEVICEEVENTS.DEVICEID, Deviceevents.DEVICEEVENTS.EVENTNAME, Deviceevents.DEVICEEVENTS.EVENTTIME }, true);
        public static Index INTERVALREADS_FK_INTERVALREADS_1_IDX = createIndex("fk_IntervalReads_1_idx", Intervalreads.INTERVALREADS, new OrderField[] { Intervalreads.INTERVALREADS.SERIALNUMBER }, false);
        public static Index INTERVALREADS_UK_INTERVAL_READ = createIndex("uk_interval_read", Intervalreads.INTERVALREADS, new OrderField[] { Intervalreads.INTERVALREADS.CHANNELNUMBER, Intervalreads.INTERVALREADS.UOM, Intervalreads.INTERVALREADS.READTIME, Intervalreads.INTERVALREADS.SERIALNUMBER }, true);
        public static Index REGISTERREADS_FK_REGISTERREADS_1_IDX = createIndex("fk_RegisterReads_1_idx", Registerreads.REGISTERREADS, new OrderField[] { Registerreads.REGISTERREADS.SERIALNUMBER }, false);
        public static Index REGISTERREADS_UK_REGISTER_KEY = createIndex("uk_register_key", Registerreads.REGISTERREADS, new OrderField[] { Registerreads.REGISTERREADS.REGISTERNUM, Registerreads.REGISTERREADS.READTIME, Registerreads.REGISTERREADS.SERIALNUMBER, Registerreads.REGISTERREADS.TOUTIER }, true);
    }
}
