/*
 * This file is generated by jOOQ.
*/
package com.dsd.db;


import com.dsd.db.tables.Device;
import com.dsd.db.tables.Deviceevents;
import com.dsd.db.tables.Intervalreads;
import com.dsd.db.tables.Registerreads;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in MeterDataStore
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>MeterDataStore.device</code>.
     */
    public static final Device DEVICE = com.dsd.db.tables.Device.DEVICE;

    /**
     * The table <code>MeterDataStore.deviceEvents</code>.
     */
    public static final Deviceevents DEVICEEVENTS = com.dsd.db.tables.Deviceevents.DEVICEEVENTS;

    /**
     * The table <code>MeterDataStore.IntervalReads</code>.
     */
    public static final Intervalreads INTERVALREADS = com.dsd.db.tables.Intervalreads.INTERVALREADS;

    /**
     * The table <code>MeterDataStore.RegisterReads</code>.
     */
    public static final Registerreads REGISTERREADS = com.dsd.db.tables.Registerreads.REGISTERREADS;
}
