/*
 * This file is generated by jOOQ.
*/
package com.dsd.db.tables;


import com.dsd.db.Indexes;
import com.dsd.db.Keys;
import com.dsd.db.Meterdatastore;
import com.dsd.db.tables.records.DeviceRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Device extends TableImpl<DeviceRecord> {

    private static final long serialVersionUID = -1046468170;

    /**
     * The reference instance of <code>MeterDataStore.device</code>
     */
    public static final Device DEVICE = new Device();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeviceRecord> getRecordType() {
        return DeviceRecord.class;
    }

    /**
     * The column <code>MeterDataStore.device.type</code>.
     */
    public final TableField<DeviceRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MeterDataStore.device.serialNumber</code>.
     */
    public final TableField<DeviceRecord, String> SERIALNUMBER = createField("serialNumber", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>MeterDataStore.device.utilityDeviceID</code>.
     */
    public final TableField<DeviceRecord, String> UTILITYDEVICEID = createField("utilityDeviceID", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>MeterDataStore.device.macID</code>.
     */
    public final TableField<DeviceRecord, String> MACID = createField("macID", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * Create a <code>MeterDataStore.device</code> table reference
     */
    public Device() {
        this(DSL.name("device"), null);
    }

    /**
     * Create an aliased <code>MeterDataStore.device</code> table reference
     */
    public Device(String alias) {
        this(DSL.name(alias), DEVICE);
    }

    /**
     * Create an aliased <code>MeterDataStore.device</code> table reference
     */
    public Device(Name alias) {
        this(alias, DEVICE);
    }

    private Device(Name alias, Table<DeviceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Device(Name alias, Table<DeviceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Meterdatastore.METERDATASTORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeviceRecord> getPrimaryKey() {
        return Keys.KEY_DEVICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeviceRecord>> getKeys() {
        return Arrays.<UniqueKey<DeviceRecord>>asList(Keys.KEY_DEVICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Device as(String alias) {
        return new Device(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Device as(Name alias) {
        return new Device(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Device rename(String name) {
        return new Device(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Device rename(Name name) {
        return new Device(name, null);
    }
}
