/*
 * This file is generated by jOOQ.
*/
package com.dsd.db.tables;


import com.dsd.db.Indexes;
import com.dsd.db.Keys;
import com.dsd.db.Meterdatastore;
import com.dsd.db.tables.records.IntervalreadsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Intervalreads extends TableImpl<IntervalreadsRecord> {

    private static final long serialVersionUID = 928996441;

    /**
     * The reference instance of <code>MeterDataStore.IntervalReads</code>
     */
    public static final Intervalreads INTERVALREADS = new Intervalreads();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IntervalreadsRecord> getRecordType() {
        return IntervalreadsRecord.class;
    }

    /**
     * The column <code>MeterDataStore.IntervalReads.channelNumber</code>.
     */
    public final TableField<IntervalreadsRecord, Integer> CHANNELNUMBER = createField("channelNumber", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MeterDataStore.IntervalReads.readValue</code>.
     */
    public final TableField<IntervalreadsRecord, Double> READVALUE = createField("readValue", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>MeterDataStore.IntervalReads.rawValue</code>.
     */
    public final TableField<IntervalreadsRecord, Integer> RAWVALUE = createField("rawValue", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MeterDataStore.IntervalReads.UOM</code>.
     */
    public final TableField<IntervalreadsRecord, String> UOM = createField("UOM", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>MeterDataStore.IntervalReads.readTime</code>.
     */
    public final TableField<IntervalreadsRecord, Timestamp> READTIME = createField("readTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MeterDataStore.IntervalReads.BlockSequenceNumber</code>.
     */
    public final TableField<IntervalreadsRecord, Integer> BLOCKSEQUENCENUMBER = createField("BlockSequenceNumber", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MeterDataStore.IntervalReads.IntervalSequenceNumber</code>.
     */
    public final TableField<IntervalreadsRecord, Integer> INTERVALSEQUENCENUMBER = createField("IntervalSequenceNumber", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MeterDataStore.IntervalReads.serialNumber</code>.
     */
    public final TableField<IntervalreadsRecord, String> SERIALNUMBER = createField("serialNumber", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * Create a <code>MeterDataStore.IntervalReads</code> table reference
     */
    public Intervalreads() {
        this(DSL.name("IntervalReads"), null);
    }

    /**
     * Create an aliased <code>MeterDataStore.IntervalReads</code> table reference
     */
    public Intervalreads(String alias) {
        this(DSL.name(alias), INTERVALREADS);
    }

    /**
     * Create an aliased <code>MeterDataStore.IntervalReads</code> table reference
     */
    public Intervalreads(Name alias) {
        this(alias, INTERVALREADS);
    }

    private Intervalreads(Name alias, Table<IntervalreadsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Intervalreads(Name alias, Table<IntervalreadsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Meterdatastore.METERDATASTORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INTERVALREADS_FK_INTERVALREADS_1_IDX, Indexes.INTERVALREADS_UK_INTERVAL_READ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IntervalreadsRecord>> getKeys() {
        return Arrays.<UniqueKey<IntervalreadsRecord>>asList(Keys.KEY_INTERVALREADS_UK_INTERVAL_READ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<IntervalreadsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<IntervalreadsRecord, ?>>asList(Keys.FK_INTERVALREADS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Intervalreads as(String alias) {
        return new Intervalreads(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Intervalreads as(Name alias) {
        return new Intervalreads(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Intervalreads rename(String name) {
        return new Intervalreads(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Intervalreads rename(Name name) {
        return new Intervalreads(name, null);
    }
}
