/*
 * This file is generated by jOOQ.
*/
package com.dsd.db.tables.records;


import com.dsd.db.tables.Device;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceRecord extends UpdatableRecordImpl<DeviceRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 405782809;

    /**
     * Setter for <code>MeterDataStore.device.type</code>.
     */
    public void setType(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MeterDataStore.device.type</code>.
     */
    public Integer getType() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MeterDataStore.device.serialNumber</code>.
     */
    public void setSerialnumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MeterDataStore.device.serialNumber</code>.
     */
    public String getSerialnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MeterDataStore.device.utilityDeviceID</code>.
     */
    public void setUtilitydeviceid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MeterDataStore.device.utilityDeviceID</code>.
     */
    public String getUtilitydeviceid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MeterDataStore.device.macID</code>.
     */
    public void setMacid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MeterDataStore.device.macID</code>.
     */
    public String getMacid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Device.DEVICE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Device.DEVICE.SERIALNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Device.DEVICE.UTILITYDEVICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Device.DEVICE.MACID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUtilitydeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMacid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUtilitydeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMacid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value1(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value2(String value) {
        setSerialnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value3(String value) {
        setUtilitydeviceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value4(String value) {
        setMacid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceRecord
     */
    public DeviceRecord() {
        super(Device.DEVICE);
    }

    /**
     * Create a detached, initialised DeviceRecord
     */
    public DeviceRecord(Integer type, String serialnumber, String utilitydeviceid, String macid) {
        super(Device.DEVICE);

        set(0, type);
        set(1, serialnumber);
        set(2, utilitydeviceid);
        set(3, macid);
    }
}
