/*
 * This file is generated by jOOQ.
*/
package com.dsd.db.tables.records;


import com.dsd.db.tables.Intervalreads;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntervalreadsRecord extends TableRecordImpl<IntervalreadsRecord> implements Record8<Integer, Double, Integer, String, Timestamp, Integer, Integer, String> {

    private static final long serialVersionUID = -1044757417;

    /**
     * Setter for <code>MeterDataStore.IntervalReads.channelNumber</code>.
     */
    public void setChannelnumber(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.channelNumber</code>.
     */
    public Integer getChannelnumber() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MeterDataStore.IntervalReads.readValue</code>.
     */
    public void setReadvalue(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.readValue</code>.
     */
    public Double getReadvalue() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>MeterDataStore.IntervalReads.rawValue</code>.
     */
    public void setRawvalue(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.rawValue</code>.
     */
    public Integer getRawvalue() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MeterDataStore.IntervalReads.UOM</code>.
     */
    public void setUom(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.UOM</code>.
     */
    public String getUom() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MeterDataStore.IntervalReads.readTime</code>.
     */
    public void setReadtime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.readTime</code>.
     */
    public Timestamp getReadtime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>MeterDataStore.IntervalReads.BlockSequenceNumber</code>.
     */
    public void setBlocksequencenumber(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.BlockSequenceNumber</code>.
     */
    public Integer getBlocksequencenumber() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MeterDataStore.IntervalReads.IntervalSequenceNumber</code>.
     */
    public void setIntervalsequencenumber(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.IntervalSequenceNumber</code>.
     */
    public Integer getIntervalsequencenumber() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MeterDataStore.IntervalReads.serialNumber</code>.
     */
    public void setSerialnumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>MeterDataStore.IntervalReads.serialNumber</code>.
     */
    public String getSerialnumber() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Double, Integer, String, Timestamp, Integer, Integer, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Double, Integer, String, Timestamp, Integer, Integer, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Intervalreads.INTERVALREADS.CHANNELNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return Intervalreads.INTERVALREADS.READVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Intervalreads.INTERVALREADS.RAWVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Intervalreads.INTERVALREADS.UOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Intervalreads.INTERVALREADS.READTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Intervalreads.INTERVALREADS.BLOCKSEQUENCENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Intervalreads.INTERVALREADS.INTERVALSEQUENCENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Intervalreads.INTERVALREADS.SERIALNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getChannelnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component2() {
        return getReadvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRawvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getReadtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getBlocksequencenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getIntervalsequencenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getChannelnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getReadvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRawvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getReadtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getBlocksequencenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIntervalsequencenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value1(Integer value) {
        setChannelnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value2(Double value) {
        setReadvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value3(Integer value) {
        setRawvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value4(String value) {
        setUom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value5(Timestamp value) {
        setReadtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value6(Integer value) {
        setBlocksequencenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value7(Integer value) {
        setIntervalsequencenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord value8(String value) {
        setSerialnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntervalreadsRecord values(Integer value1, Double value2, Integer value3, String value4, Timestamp value5, Integer value6, Integer value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntervalreadsRecord
     */
    public IntervalreadsRecord() {
        super(Intervalreads.INTERVALREADS);
    }

    /**
     * Create a detached, initialised IntervalreadsRecord
     */
    public IntervalreadsRecord(Integer channelnumber, Double readvalue, Integer rawvalue, String uom, Timestamp readtime, Integer blocksequencenumber, Integer intervalsequencenumber, String serialnumber) {
        super(Intervalreads.INTERVALREADS);

        set(0, channelnumber);
        set(1, readvalue);
        set(2, rawvalue);
        set(3, uom);
        set(4, readtime);
        set(5, blocksequencenumber);
        set(6, intervalsequencenumber);
        set(7, serialnumber);
    }
}
